name: Continuous Integration
# This action works with publish the npm package of blindex stablecoins if needed
on:
  push:
    branches:
      - kazaz/lago-219-stablecoins-package

jobs:
  check-if-publish-needed:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      localPackageVersion: ${{ steps.localPackageVersion.outputs.localPackageVersion }}
      remotePackageVersion: ${{ steps.remotePackageVersion.outputs.remotePackageVersion }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running
          ref: ${{ github.head_ref }}
      - name: Get Package Name
        id: packageName
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "./@blindex/stablecoins/package.json"
          prop_path: "name"
      - name: Get Local Package Version
        id: localPackageVersion
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "./@blindex/stablecoins/package.json"
          prop_path: "version"
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: npm
      - name: Get Remote Package Version
        id: remotePackageVersion
        run: |
          $remotePackageVersion=(npm view ${{steps.packageName.outputs.prop}} version)
          echo "::set-output name=localPackageVersion::${{steps.localPackageVersion.outputs.prop}}"
          echo "::set-output name=remotePackageVersion::$remotePackageVersion"

  # publish-npmpackage:
  #   runs-on: ubuntu-latest
  #   needs: check-if-publish-needed
  #   if: ${{needs.check-if-publish-needed.outputs.localPackageVersion != needs.check-if-publish-needed.outputs.remotePackageVersion}}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         # Make sure the actual branch is checked out when running
  #         ref: ${{ github.head_ref }}
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: "16.x"
  #         cache: npm
  #     - name: Install Node modules
  #       run: npm ci
  #     - name: Compile
  #       run: npm run compile
  #     - name: Publish npm package
  #     - env:
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #       run: npm run publish-blindex-package
